[mypy]
strict = True

[mypy-obase.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-docker.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-asyncpg.*]
ignore_missing_imports = True
follow_imports = skip
