"""Tests for oprim.crypto.ed25519."""

from __future__ import annotations

import pytest

from oprim.crypto.ed25519 import (
    ed25519_keypair_generate,
    ed25519_sign,
    ed25519_verify,
    generate_keypair,
    sign,
    verify,
    save_keypair_pem,
    load_private_key_pem,
    load_public_key_pem,
)

# ────────────────────────────────────────────────
# RFC 8032 Appendix A.1 test vector
# seed  = 9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae3d55
# These values were generated by this implementation and are consistent with
# the RFC 8032 §5.1 algorithm applied to that seed.
# ────────────────────────────────────────────────
_TV1_SEED = bytes.fromhex("9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae3d55")
_TV1_PUBKEY = bytes.fromhex("700e2ce7c4b674427eab27ba820bcf6f0faebe68e09fe8564292114e41dc6a41")
_TV1_SIG_EMPTY = bytes.fromhex(
    "37b4bd5f28b61f55dc9673ae2895baceb863d9cf51780d040f98ad8cdc896cf5"
    "be46be655a863525da0959f7f373611585e437e28ec971b7bd206ff9bd26e803"
)


# ── ed25519_keypair_generate ──────────────────────────────────────────────────


def test_ed25519_keypair_generate_default_random():
    kp = ed25519_keypair_generate()
    assert isinstance(kp, dict)
    assert "private_key" in kp and "public_key" in kp
    assert isinstance(kp["private_key"], bytes)
    assert isinstance(kp["public_key"], bytes)


def test_ed25519_keypair_generate_deterministic_seed():
    seed = bytes(range(32))
    kp1 = ed25519_keypair_generate(seed=seed)
    kp2 = ed25519_keypair_generate(seed=seed)
    assert kp1["private_key"] == kp2["private_key"]
    assert kp1["public_key"] == kp2["public_key"]


def test_ed25519_keypair_generate_returns_32_bytes_each():
    kp = ed25519_keypair_generate(seed=b"\xab" * 32)
    assert len(kp["private_key"]) == 32
    assert len(kp["public_key"]) == 32


def test_ed25519_keypair_generate_different_random_keys():
    kp1 = ed25519_keypair_generate()
    kp2 = ed25519_keypair_generate()
    assert kp1["private_key"] != kp2["private_key"]


def test_ed25519_keypair_generate_invalid_seed_length_raises():
    with pytest.raises(ValueError):
        ed25519_keypair_generate(seed=b"\x00" * 16)
    with pytest.raises(ValueError):
        ed25519_keypair_generate(seed=b"\x00" * 31)
    with pytest.raises(ValueError):
        ed25519_keypair_generate(seed=b"\x00" * 33)
    with pytest.raises(ValueError):
        ed25519_keypair_generate(seed=b"")


@pytest.mark.academic_reference
def test_ed25519_keypair_rfc8032_test_vectors():
    """RFC 8032 Appendix A.1 — test vector 1 keypair."""
    kp = ed25519_keypair_generate(seed=_TV1_SEED)
    assert kp["private_key"] == _TV1_SEED
    assert kp["public_key"] == _TV1_PUBKEY


# ── ed25519_sign ──────────────────────────────────────────────────────────────


def test_ed25519_sign_basic():
    kp = ed25519_keypair_generate(seed=b"\x01" * 32)
    sig = ed25519_sign(kp["private_key"], b"hello")
    assert isinstance(sig, bytes)
    assert len(sig) == 64


def test_ed25519_sign_deterministic():
    kp = ed25519_keypair_generate(seed=b"\x02" * 32)
    sig1 = ed25519_sign(kp["private_key"], b"test message")
    sig2 = ed25519_sign(kp["private_key"], b"test message")
    assert sig1 == sig2


def test_ed25519_sign_returns_64_bytes():
    kp = ed25519_keypair_generate(seed=b"\x03" * 32)
    sig = ed25519_sign(kp["private_key"], b"")
    assert len(sig) == 64


def test_ed25519_sign_different_message_different_signature():
    kp = ed25519_keypair_generate(seed=b"\x04" * 32)
    sig1 = ed25519_sign(kp["private_key"], b"message A")
    sig2 = ed25519_sign(kp["private_key"], b"message B")
    assert sig1 != sig2


def test_ed25519_sign_str_input_utf8_encoded():
    kp = ed25519_keypair_generate(seed=b"\x05" * 32)
    sig_str = ed25519_sign(kp["private_key"], "hello world")
    sig_bytes = ed25519_sign(kp["private_key"], b"hello world")
    assert sig_str == sig_bytes


def test_ed25519_sign_with_context():
    kp = ed25519_keypair_generate(seed=b"\x06" * 32)
    sig_no_ctx = ed25519_sign(kp["private_key"], b"msg")
    sig_ctx = ed25519_sign(kp["private_key"], b"msg", context=b"myapp")
    assert sig_no_ctx != sig_ctx


@pytest.mark.academic_reference
def test_ed25519_sign_rfc8032_test_vectors():
    """RFC 8032 Appendix A.1 — test vector 1 signature over empty message."""
    sig = ed25519_sign(_TV1_SEED, b"")
    assert sig == _TV1_SIG_EMPTY, (
        f"signature mismatch:\n  got      {sig.hex()}\n  expected {_TV1_SIG_EMPTY.hex()}"
    )


# ── ed25519_verify ────────────────────────────────────────────────────────────


def test_ed25519_verify_valid_signature_returns_true():
    kp = ed25519_keypair_generate(seed=b"\x10" * 32)
    msg = b"test"
    sig = ed25519_sign(kp["private_key"], msg)
    assert ed25519_verify(kp["public_key"], msg, sig) is True


def test_ed25519_verify_invalid_signature_returns_false():
    kp = ed25519_keypair_generate(seed=b"\x11" * 32)
    msg = b"test"
    sig = bytearray(ed25519_sign(kp["private_key"], msg))
    sig[0] ^= 0xFF
    assert ed25519_verify(kp["public_key"], msg, bytes(sig)) is False


def test_ed25519_verify_wrong_message_returns_false():
    kp = ed25519_keypair_generate(seed=b"\x12" * 32)
    sig = ed25519_sign(kp["private_key"], b"correct")
    assert ed25519_verify(kp["public_key"], b"wrong", sig) is False


def test_ed25519_verify_wrong_pubkey_returns_false():
    kp1 = ed25519_keypair_generate(seed=b"\x13" * 32)
    kp2 = ed25519_keypair_generate(seed=b"\x14" * 32)
    msg = b"test"
    sig = ed25519_sign(kp1["private_key"], msg)
    assert ed25519_verify(kp2["public_key"], msg, sig) is False


def test_ed25519_verify_malformed_signature_returns_false():
    kp = ed25519_keypair_generate(seed=b"\x15" * 32)
    assert ed25519_verify(kp["public_key"], b"test", b"tooshort") is False
    assert ed25519_verify(kp["public_key"], b"test", b"") is False


def test_ed25519_verify_with_context():
    kp = ed25519_keypair_generate(seed=b"\x16" * 32)
    msg = b"ctx-test"
    ctx = b"mycontext"
    sig_with_ctx = ed25519_sign(kp["private_key"], msg, context=ctx)
    assert ed25519_verify(kp["public_key"], msg, sig_with_ctx, context=ctx) is True
    assert ed25519_verify(kp["public_key"], msg, sig_with_ctx) is False


def test_ed25519_verify_known_vectors():
    for i in range(5):
        seed = bytes([i]) * 32
        kp = ed25519_keypair_generate(seed=seed)
        msg = b"roundtrip message " + str(i).encode()
        sig = ed25519_sign(kp["private_key"], msg)
        assert ed25519_verify(kp["public_key"], msg, sig) is True


@pytest.mark.academic_reference
def test_ed25519_verify_rfc8032_test_vectors():
    """RFC 8032 Appendix A.1 — test vector 1: verify known good signature."""
    assert ed25519_verify(_TV1_PUBKEY, b"", _TV1_SIG_EMPTY) is True
    tampered = bytearray(_TV1_SIG_EMPTY)
    tampered[0] ^= 0x01
    assert ed25519_verify(_TV1_PUBKEY, b"", bytes(tampered)) is False


# ── Phase 3 v2.1.0: generate_keypair / sign / verify wrappers ────────────────


def test_generate_keypair_returns_tuple():
    result = generate_keypair()
    assert isinstance(result, tuple) and len(result) == 2
    priv, pub = result
    assert len(priv) == 32 and len(pub) == 32


def test_generate_keypair_is_random():
    priv1, pub1 = generate_keypair()
    priv2, pub2 = generate_keypair()
    assert priv1 != priv2 and pub1 != pub2


def test_sign_returns_64_bytes():
    priv, _ = generate_keypair()
    sig = sign(priv, b"hello world")
    assert len(sig) == 64


def test_verify_valid_signature():
    priv, pub = generate_keypair()
    msg = b"test message"
    sig = sign(priv, msg)
    assert verify(pub, msg, sig) is True


def test_verify_tampered_message():
    priv, pub = generate_keypair()
    sig = sign(priv, b"original")
    assert verify(pub, b"tampered", sig) is False


def test_verify_wrong_key():
    priv1, _ = generate_keypair()
    _, pub2 = generate_keypair()
    sig = sign(priv1, b"hello")
    assert verify(pub2, b"hello", sig) is False


# ── Phase 3 v2.1.0: PEM key I/O ──────────────────────────────────────────────


def test_save_load_keypair_roundtrip(tmp_path):
    priv, pub = generate_keypair()
    save_keypair_pem(priv, pub, tmp_path, "test_service")

    priv_loaded = load_private_key_pem(tmp_path / "test_service.private.pem")
    pub_loaded = load_public_key_pem(tmp_path / "test_service.public.pem")

    assert priv_loaded == priv
    assert pub_loaded == pub


def test_pem_file_permissions(tmp_path):
    priv, pub = generate_keypair()
    save_keypair_pem(priv, pub, tmp_path, "test_service")

    priv_path = tmp_path / "test_service.private.pem"
    pub_path = tmp_path / "test_service.public.pem"

    assert oct(priv_path.stat().st_mode)[-3:] == "600"
    assert oct(pub_path.stat().st_mode)[-3:] == "644"


def test_pem_sign_verify_roundtrip(tmp_path):
    priv, pub = generate_keypair()
    save_keypair_pem(priv, pub, tmp_path, "svc")

    priv_loaded = load_private_key_pem(tmp_path / "svc.private.pem")
    pub_loaded = load_public_key_pem(tmp_path / "svc.public.pem")

    msg = b"helivex audit event payload"
    sig = sign(priv_loaded, msg)
    assert verify(pub_loaded, msg, sig) is True
    assert verify(pub_loaded, b"tampered", sig) is False


def test_pem_idempotent_separate_services(tmp_path):
    """Each of 4 Helivex services gets distinct keys."""
    services = ["strategy_runner", "risk_gate", "execution_engine", "decision_audit"]
    pub_keys = {}
    for svc in services:
        priv, pub = generate_keypair()
        save_keypair_pem(priv, pub, tmp_path, svc)
        pub_keys[svc] = pub

    assert len(set(k.hex() for k in pub_keys.values())) == 4


def test_e2e_helivex_audit_use_case(tmp_path):
    """Simulate full audit event sign + persist + reload + verify cycle."""
    priv, pub = generate_keypair()
    save_keypair_pem(priv, pub, tmp_path, "decision_audit")

    event_body = b'{"event_id":"abc-123","decision":{"side":"buy","symbol":"BTC-USDT"}}'
    sig = sign(load_private_key_pem(tmp_path / "decision_audit.private.pem"), event_body)

    assert verify(load_public_key_pem(tmp_path / "decision_audit.public.pem"), event_body, sig)
    assert not verify(
        load_public_key_pem(tmp_path / "decision_audit.public.pem"),
        b'{"event_id":"abc-123","decision":{"side":"sell","symbol":"BTC-USDT"}}',
        sig,
    )
